name: "Run GUT Tests for Godot4"
description: "Run GUT tests for a Godot project"
author: "josephbmanley"
inputs:
  containerImage:
    description: "The container to run tests inside of."
    default: "barichello/godot-ci:latest"
  useContainer:
    description: "Boolean value of whether or not to run container."
    default: true
  godotExecutable:
    description: "Path of Godot binary to call when running GUT tests."
    default: godot
  gutConfigPath:
    description: "Path to gut config relative to directory"
    default: ''
  godotFlags:
    description: "Extra flags to pass to godot, e.g. --headless"
    default: '--headless'
  directory:
    description: "The name directory to run tests in."
runs:
  using: "node20"
  main: "dist/index.js"
branding:
  icon: cpu
  color: yellow