name: Test Action

on: [push, pull_request]

jobs:
  TestAction:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run Action
      id: run_tests
      uses: ./
      with:
        directory: test_proj